src/WineStore.WebApp.MVC/Controllers/CarrinhoController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using WineStore.Catalogo.Application.Services;
using WineStore.Core.Mediator;
using WineStore.Core.Messages.CommonMessages.Notifications;
using WineStore.Vendas.Application.Commands;
using WineStore.Vendas.Application.Queries;
using WineStore.Vendas.Application.Queries.ViewModels;

namespace WineStore.WebApp.MVC.Controllers
{
    public class CarrinhoController : ControllerBase
    {
        private readonly IProdutoAppService _produtoAppService;
        private readonly IMediatorHandler _mediatorHandler;
        private readonly IPedidoQueries _pedidoQueries;
        public CarrinhoController(IProdutoAppService produtoAppService,
                                  INotificationHandler<DomainNotification> notifications,
                                  IMediatorHandler mediatorHandler, 
                                  IPedidoQueries pedidoQueries) : base(notifications, mediatorHandler)
        {
            _produtoAppService = produtoAppService;
            _mediatorHandler = mediatorHandler;
            _pedidoQueries = pedidoQueries;
        }

        [Route("meu-carrinho")]
        public async Task<IActionResult> Index()
        {
            return View(await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("meu-carrinho")]
        public async Task<IActionResult> AdicionarItem(Guid id, int quantidade)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if (produto == null) return BadRequest();

            if (produto.QuantidadeEstoque < quantidade)
            {
                TempData["Erro"] = "Produto com estoque insuficiente";
                return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
            }

            var command = new AdicionarItemPedidoCommand(ClienteId, produto.Id, produto.Nome, quantidade, produto.Valor);
            await _mediatorHandler.EnviarComando(command);


            if(OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            TempData["Erros"] = ObterMensagensErro();
            return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
        }

        [HttpPost]
        [Route("remover-item")]
        public async Task<IActionResult> RemoverItem(Guid id)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if (produto == null) return BadRequest();

            var command = new RemoverItemPedidoCommand(ClienteId, produto.Id);
            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("atualizar-item")]
        public async Task<IActionResult> AtualizarItem(Guid id, int quantidade)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if (produto == null) return BadRequest();

            var command = new AtualizarItemPedidoCommand(ClienteId, produto.Id, quantidade);
            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("aplicar-voucher")]
        public async Task<IActionResult> AplicarVoucher(string voucherCodigo)
        {
            var command = new AplicarVoucherPedidoCommand(ClienteId, voucherCodigo);
            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [Route("resumo-da-compra")]
        public async Task<IActionResult> ResumoDaCompra()
        {
            return View(await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("iniciar-pedido")]
        public async Task<IActionResult> IniciarPedido(CarrinhoViewModel carrinhoViewModel)
        {
            var carrinho = await _pedidoQueries.ObterCarrinhoCliente(ClienteId);
            
            var command = new IniciarPedidoCommand(carrinho.PedidoId, ClienteId, carrinho.ValorTotal, carrinhoViewModel.Pagamento.NomeCartao,
                carrinhoViewModel.Pagamento.NumeroCartao, carrinhoViewModel.Pagamento.ExpiracaoCartao, carrinhoViewModel.Pagamento.CvvCartao);

            await _mediatorHandler.EnviarComando(command);
            
            if (OperacaoValida())
            {
                return RedirectToAction("Index", "Pedido");
            }

            return View("ResumoDaCompra", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }
    }
}

src/WineStore.WebApp.MVC/Controllers/VitrineController.cs
using Microsoft.AspNetCore.Mvc;
using WineStore.Catalogo.Application.Services;

namespace WineStore.WebApp.MVC.Controllers
{
    public class VitrineController : Controller
    {
        private readonly IProdutoAppService _produtoAppService;

        public VitrineController(IProdutoAppService produtoAppService)
        {
            _produtoAppService = produtoAppService;
        }

        [HttpGet]
        [Route("vitrine")]
        public async Task<IActionResult> Index()
        {
            return View(await _produtoAppService.ObterTodos());
        }

        [HttpGet]
        [Route("produto-detalhe/{id}")]
        public async Task<IActionResult> ProdutoDetalhe(Guid id)
        {
            return View(await _produtoAppService.ObterPorId(id));
        }
    }
}

src/WineStore.WebApp.MVC/Extensions/SummaryViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using WineStore.Core.Messages.CommonMessages.Notifications;

namespace WineStore.WebApp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.ObterNotificacoes());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

src/WineStore.WebApp.MVC/Views/Vitrine/Index.cshtml
@model IEnumerable<WineStore.Catalogo.Application.ViewModels.ProdutoViewModel>

@{
    ViewData["Title"] = "Vitrine";
}
<style>
    h4 {
        font-weight: 600;
    }

    p {
        font-size: 12px;
        margin-top: 5px;
    }

    .price {
        font-size: 30px;
        margin: 0 auto;
        color: #333;
    }

    .right {
        float: right;
        border-bottom: 2px solid #4B8E4B;
    }

    .thumbnail {
        opacity: 0.70;
        -webkit-transition: all 0.5s;
        transition: all 0.5s;
    }

        .thumbnail:hover {
            opacity: 1.00;
            box-shadow: 0px 0px 10px #4bc6ff;
        }

    .line {
        margin-bottom: 5px;
    }

    @@media screen and (max-width: 770px) {
        .right {
            float: left;
            width: 100%;
        }
    }

    .product_view .modal-dialog {
        max-width: 800px;
        width: 100%;
    }

    .pre-cost {
        text-decoration: line-through;
        color: #a5a5a5;
    }

    .space-ten {
        padding: 10px 0;
    }
</style>
<div class="container">

    <h1>Vitrine de Produtos</h1>
    <br />
    <div class="row">
        <!-- BEGIN PRODUCTS -->
        @{
            foreach (var produto in Model.OrderBy(p=>p.CategoriaId))
            {
            <div class="col-md-3 col-sm-6">
                <span class="thumbnail">
                    <a asp-controller="Vitrine" asp-action="ProdutoDetalhe" asp-route-id="@produto.Id"><img width="200" height="200" src="~/Images/@produto.Imagem" /></a>
                    <h4>@produto.Nome</h4>
                    <p>Apenas @produto.QuantidadeEstoque em estoque!</p>
                    <p>@produto.Descricao</p>
                    <hr class="line">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <p class="price">@produto.Valor.ToString("C")</p>
                        </div>
                    </div>
                </span>
            </div>
            }
        }

        <!-- END PRODUCTS -->
    </div>
</div>

src/WineStore.WebApp.MVC/Views/Vitrine/ProdutoDetalhe.cshtml
@model WineStore.Catalogo.Application.ViewModels.ProdutoViewModel
@{
    ViewData["Title"] = "Produto Detalhe";
}

<style>
    ul > li {
        margin-right: 25px;
        font-weight: lighter;
        cursor: pointer
    }

    li.active {
        border-bottom: 3px solid silver;
    }

    .item-photo {
        display: flex;
        justify-content: center;
        align-items: center;
        border-right: 1px solid #f6f6f6;
    }

    .menu-items {
        list-style-type: none;
        font-size: 11px;
        display: inline-flex;
        margin-bottom: 0;
        margin-top: 20px
    }

    .btn-success {
        width: 100%;
        border-radius: 0;
    }

    .section {
        width: 100%;
        margin-left: -15px;
        padding: 2px;
        padding-left: 15px;
        padding-right: 15px;
        background: #f8f9f9
    }

    .title-price {
        margin-top: 30px;
        margin-bottom: 0;
        color: black
    }

    .title-attr {
        margin-top: 0;
        margin-bottom: 0;
        color: black;
    }

    .btn-minus {
        cursor: pointer;
        font-size: 7px;
        display: flex;
        align-items: center;
        padding: 5px;
        padding-left: 10px;
        padding-right: 10px;
        border: 1px solid gray;
        border-radius: 2px;
        border-right: 0;
    }

    .btn-plus {
        cursor: pointer;
        font-size: 7px;
        display: flex;
        align-items: center;
        padding: 5px;
        padding-left: 10px;
        padding-right: 10px;
        border: 1px solid gray;
        border-radius: 2px;
        border-left: 0;
    }

    div.section > div {
        width: 100%;
        display: inline-flex;
    }

        div.section > div > input {
            margin: 0;
            padding-left: 5px;
            font-size: 10px;
            padding-right: 5px;
            max-width: 18%;
            text-align: center;
        }

    .attr, .attr2 {
        cursor: pointer;
        margin-right: 5px;
        height: 20px;
        font-size: 10px;
        padding: 2px;
        border: 1px solid gray;
        border-radius: 2px;
    }

        .attr.active, .attr2.active {
            border: 1px solid orange;
        }

    @@media (max-width: 426px) {
        .container {
            margin-top: 0px !important;
        }

            .container > .row {
                padding: 0 !important;
            }

                .container > .row > .col-xs-12.col-sm-5 {
                    padding-right: 0;
                }

                .container > .row > .col-xs-12.col-sm-9 > div > p {
                    padding-left: 0 !important;
                    padding-right: 0 !important;
                }

                .container > .row > .col-xs-12.col-sm-9 > div > ul {
                    padding-left: 10px !important;
                }

        .section {
            width: 104%;
        }

        .menu-items {
            padding-left: 0;
        }
    }
</style>
<div class="container">
    
    <vc:summary />

    <div class="row">
        <div class="col-xs-4 item-photo">

            <img width="400" height="400" src="~/Images/@Model.Imagem"/>
        </div>
        <div class="col-xs-5" style="border: 20px solid white">
            <h3>@Model.Nome</h3>

            <h6 class="title-price"><small>OFERTA</small></h6>
            <h3 style="margin-top: 0px;">@Model.Valor.ToString("C")</h3>

            <p>Apenas @Model.QuantidadeEstoque em estoque!</p>
            <p>@Model.Descricao</p>
            <form method="post" asp-controller="Carrinho" asp-action="AdicionarItem">

                <input type="hidden" id="Id" name="Id" value="@Model.Id"/>

                <div class="section" style="padding-bottom: 20px;">
                    <h6 class="title-attr"><small>QUANTIDADE</small></h6>
                    <div>
                        <div class="btn-minus"><span style="font-size: 15px">-</span></div>
                        <input id="quantidade" name="quantidade" style="font-size: 15px" type="text" value="1"/>
                        <div class="btn-plus"><span style="font-size: 15px">+</span></div>
                    </div>
                </div>

                <!-- Botoes de compra -->
                <div class="section" style="padding-bottom: 20px;">
                    <button type="submit" class="btn btn-success"><span style="margin-right: 20px" aria-hidden="true"></span> Comprar agora!</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        $(document).ready(function(){
            //-- Click on detail
            $("ul.menu-items > li").on("click",function(){
                $("ul.menu-items > li").removeClass("active");
                $(this).addClass("active");
            })

            $(".attr,.attr2").on("click",function(){
                var clase = $(this).attr("class");

                $("." + clase).removeClass("active");
                $(this).addClass("active");
            })

            //-- Click on QUANTITY
            $(".btn-minus").on("click",function(){
                var now = $(".section > div > input").val();
                if ($.isNumeric(now)){
                    if (parseInt(now) -1 > 0){ now--;}
                    $(".section > div > input").val(now);
                }else{
                    $(".section > div > input").val("1");
                }
            })
            $(".btn-plus").on("click",function(){
                var now = $(".section > div > input").val();
                if ($.isNumeric(now)){
                    $(".section > div > input").val(parseInt(now)+1);
                }else{
                    $(".section > div > input").val("1");
                }
            })
        })
    </script>
}